### PR TITLE
Added LWJGL 3.x module and implementation in regards to issue #314

### PR DESCRIPTION
**Pull request by DannyJo**
Here you go phr00t :)

### CODE REVIEW

**Comment by DannyJo** [comment]
Btw, in order to use it you only need to stop using jme3-lwjgl and start using the jme3-lwjgl3 module. There is no need to set a different renderer anywhere.

**Comment by phr00t** [comment]
sweet, let's go! :D

**Comment by phr00t** [comment]
I get this error when trying to use jme3-lwjgl3 instead of jme3-lwjgl:

"Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/opengl/GLDebugMessageARBCallback
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.jme3.system.JmeDesktopSystem.newContextLwjgl(JmeDesktopSystem.java:191)
	at com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:271)
	at com.jme3.system.JmeSystem.newContext(JmeSystem.java:162)
	at com.jme3.app.Application.start(Application.java:444)
	at jmevr.app.VRApplication.start(VRApplication.java:258)
	at Game.Main.StartGame(Main.java:499)
	at Game.Main.main(Main.java:454)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.GLDebugMessageARBCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Java Result: 1"

Also... where are the native libraries for LWJGL3? Do I need to put together a native library jar myself?

**Comment by phr00t** [comment]
@DannyJo I get this error when trying to use jme3-lwjgl3 instead of jme3-lwjgl:

"Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/opengl/GLDebugMessageARBCallback
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.jme3.system.JmeDesktopSystem.newContextLwjgl(JmeDesktopSystem.java:191)
at com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:271)
at com.jme3.system.JmeSystem.newContext(JmeSystem.java:162)
at com.jme3.app.Application.start(Application.java:444)
at jmevr.app.VRApplication.start(VRApplication.java:258)
at Game.Main.StartGame(Main.java:499)
at Game.Main.main(Main.java:454)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.GLDebugMessageARBCallback
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 9 more
Java Result: 1"

Also... where are the native libraries for LWJGL3? Do I need to put together a native library jar myself?

**Comment by DannyJo** [comment]
Are you still using 3.0.0b-SNAPSHOT, I believe they are currently making API changes, the master branch of jme now uses 3.0.0a for a bit more stable running.

The natives should come from the included platform jar files which are in the build.gradle as far as I know.

**Comment by phr00t** [comment]
Probably. How do I switch back to 3.0.0a like the master branch?

I still can't seem to locate the natives... all I see are the usual lwjgl-platform-natives-windows etc. files, which I presume still have the v2 natives. I presume there are v3 natives... somewhere...?

**Comment by DannyJo** [comment]
You simply change the version in the build.gradle file to 3.0.0a instead of 3.0.0b-SNAPSHOT and then you need to make a minor code change or so in LwjglContext.java, see https://github.com/jMonkeyEngine/jmonkeyengine/commit/f4706373618215e3868f9779b68f8da4918ebd37 for the exact changes. Another this was a missing line of code for the GL context which was added in https://github.com/jMonkeyEngine/jmonkeyengine/commit/14349695a963940b9d25418af5b36224b26b89c3

Maybe if you merged in the latest changes from master you would get these.

The natives are included as dependencies in the build.gradle script using a special classifier.

```
    compile 'org.lwjgl:lwjgl:3.0.0a'
    compile group: 'org.lwjgl', name: 'lwjgl-platform', version: '3.0.0a', classifier: 'natives-windows'
    compile group: 'org.lwjgl', name: 'lwjgl-platform', version: '3.0.0a', classifier: 'natives-linux'
    compile group: 'org.lwjgl', name: 'lwjgl-platform', version: '3.0.0a', classifier: 'natives-osx'
```

In your IDE you might be able to see the referenced external libs and there should be some 3 jars there, one for each platform just like for LWJGL 2.9.3

At the moment there seems to be an issue running this module on Linux though, not sure why yet.

**Comment by phr00t** [comment]
I've pulled those two commits into my repository & rebuilt. I still get the same exception...

This is the output I get when looking for lwjgl-platform files, after building:

Phr00t@SomebodyPC /cygdrive/d/jme3_gitrw/jmonkeyengine
$ find | grep lwjgl-platform
./dist/lib/lwjgl-platform-natives-linux.jar
./dist/lib/lwjgl-platform-natives-osx.jar
./dist/lib/lwjgl-platform-natives-windows.jar
./lib/lwjgl-platform-natives-linux.jar
./lib/lwjgl-platform-natives-osx.jar
./lib/lwjgl-platform-natives-windows.jar
./sdk/build/cluster/libs/lwjgl-platform-2.9.3-natives-linux.jar
./sdk/build/cluster/libs/lwjgl-platform-2.9.3-natives-osx.jar
./sdk/build/cluster/libs/lwjgl-platform-2.9.3-natives-windows.jar
./sdk/build/cluster/modules/ext/lwjgl-platform-2.9.3-natives-linux.jar
./sdk/build/cluster/modules/ext/lwjgl-platform-2.9.3-natives-osx.jar
./sdk/build/cluster/modules/ext/lwjgl-platform-2.9.3-natives-windows.jar
./sdk/jme3-core-libraries/release/modules/ext/lwjgl-platform-2.9.3-natives-linux.jar
./sdk/jme3-core-libraries/release/modules/ext/lwjgl-platform-2.9.3-natives-osx.jar
./sdk/jme3-core-libraries/release/modules/ext/lwjgl-platform-2.9.3-natives-windows.jar
./sdk/jme3-project-libraries/release/libs/lwjgl-platform-2.9.3-natives-linux.jar
./sdk/jme3-project-libraries/release/libs/lwjgl-platform-2.9.3-natives-osx.jar
./sdk/jme3-project-libraries/release/libs/lwjgl-platform-2.9.3-natives-windows.jar

The ones in ./dist/lib & ./lib are 2.9.4 ones I made months ago...

**Comment by phr00t** [comment]
Hey @DannyJo , making another attempt at getting LWJGL3 working. I downloaded the native & lwjgl.jar files from the LWJGL main site for 3.0.0a. I added the lwjgl.jar to my project, and created 3 "native" JAR files as seen here:

https://github.com/phr00t/jmonkeyengine/tree/master/lib/LWJGL%203.0.0a

I dumped all of the native libraries for each operating system in each. When trying to run my project, I get this error:

Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.LWJGLUtil.loadLibrarySystem(LWJGLUtil.java:337)
	at org.lwjgl.Sys$1.run(Sys.java:36)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.<clinit>(Sys.java:33)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:406)
	at java.lang.Thread.run(Thread.java:745)

I assume it is having trouble getting the lwjgl.dll file, which is in the lwjgl3-platform-natives-windows.jar file. Perhaps it isn't getting extracted correctly?

**Comment by DannyJo** [comment]
Right, I'm going to have a go at creating a simple jme3 demo project using the latest snapshot and running lwjgl3 and see how that goes.

**Comment by phr00t** [comment]
OK, I think I am getting a bit closer here. However, I'm having trouble with the OpenAL.dll being loaded. I do see the LWJGL window briefly appear, so I *think* it is getting that library loaded, at least... I put OpenAL.dll inside a "lwjgl3-platform-natives.jar" file, and it is located /native/windows/OpenAL.dll inside the JAR. lwjgl.dll is in the same location.

SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.ExceptionInInitializerError
	at org.lwjgl.openal.ALDevice.create(ALDevice.java:71)
	at org.lwjgl.openal.ALContext.create(ALContext.java:90)
	at com.jme3.audio.lwjgl.LwjglALC.createALC(LwjglALC.java:48)
	at com.jme3.audio.openal.ALAudioRenderer.initOpenAL(ALAudioRenderer.java:95)
	at com.jme3.audio.openal.ALAudioRenderer.initialize(ALAudioRenderer.java:225)
	at com.jme3.app.Application.initAudio(Application.java:266)
	at com.jme3.app.Application.initialize(Application.java:584)
	at jmevr.app.VRApplication.initialize(VRApplication.java:493)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:310)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:408)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to load library: .\OpenAL.dll (error code = 0)
	at org.lwjgl.system.windows.WindowsPlatform.windowsThrowException(WindowsPlatform.java:34)
	at org.lwjgl.system.windows.WindowsLibrary.<init>(WindowsLibrary.java:33)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:54)
	at org.lwjgl.LWJGLUtil$2.load(LWJGLUtil.java:402)
	at org.lwjgl.LWJGLUtil$2.load(LWJGLUtil.java:399)
	at org.lwjgl.LWJGLUtil.loadLibrary(LWJGLUtil.java:410)
	at org.lwjgl.LWJGLUtil.loadLibraryNative(LWJGLUtil.java:370)
	at org.lwjgl.openal.ALC.create(ALC.java:55)
	at org.lwjgl.openal.ALC.create(ALC.java:48)
	at org.lwjgl.openal.ALC.<clinit>(ALC.java:27)

I still don't see where your natives are being unpacked from, which is why I'm making my own.

**Pull request merged**
