### PR TITLE
Revert some unwanted changes from 97c883

### PR DESCRIPTION
**Pull request by d235j**
This reverts some changes which prevent SDK build from working correctly out-of-box. With this PR, the instructions at http://wiki.jmonkeyengine.org/doku.php/sdk:build_platform can be used to compile this fork.

### CODE REVIEW

**Comment by phr00t** [comment]
Not sure why the files seem so different from the main jME3 SDK branch. For example, https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/sdk/nbproject/project.xml is really small, while mine is huge. I don't recall making any specific SDK changes, so I don't see why my files should be any different.

The changes in jme3-jogl.xml... why are they being rolled back from 2.3.1 to 2.2.0?

**Comment by d235j** [comment]
Oh, I didn't intend to roll them back — I just made them consistent with upstream JME. I can bring them back to 2.3.1 etc if this was intentional.

**Comment by d235j** [comment]
And odd — your sdk/nbproject/project.xml looks correct, unless I'm seeing things wrong.

**Comment by d235j** [comment]
Other anomalies are present at the following locations — mainly additional .jars, which I'm not sure where they came from:
https://github.com/phr00t/jmonkeyengine/pull/84/files#diff-6983cfad22dccafcb17f3bce1ccf107bL10
This adds android.jar to jme3-android.

https://github.com/phr00t/jmonkeyengine/pull/84/files#diff-c0f5aef683c6fdca5b43675862b22128L10
This adds core-0.27.jar, dense64-0.27.jar, simple-0.27.jar, and denseC64-0.27.jar to jme3-blender.

**Comment by d235j** [comment]
Oh, I think what happened is that you committed after building, and committed all the local modifications that the build scripts made to the files. Unfortunately it seems that building causes those files to have local modifications made to them.

**Comment by d235j** [comment]
Looks like android.jar was removed from upstream here: https://github.com/JMonkeyEngine/jmonkeyengine/commit/1fa4eb441d392640e0f672c5d17435002fa83744

And it looks like the additional libs in jme3-blender.xml were added in this changeset: https://github.com/phr00t/jmonkeyengine/commit/5779064b4af8b9b285c1ad8700e048c052e7a371

**Comment by phr00t** [comment]
My files should look as close to the main jME3 branch as possible, while still building according to the instructions. If the additional libs in jme3-blender.xml are there, they should be in this repository too.

**Comment by d235j** [comment]
They are not in the main jME3 branch (compare https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/sdk/jme3-project-baselibs/src/com/jme3/gde/project/baselibs/jme3-blender.xml to https://github.com/phr00t/jmonkeyengine/blob/master/sdk/jme3-project-baselibs/src/com/jme3/gde/project/baselibs/jme3-blender.xml) — so I assume they should stay out, then.

**Comment by phr00t** [comment]
OK, they should stay out then. Does that make everything line up good enough now, as far as you know?

**Comment by d235j** [comment]
Yes, as far as I can tell. The complete SDK now builds correctly as described in the instructions (gradlew.bat build, then open jmonkeyengine\sdk in NetBeans and build the project).

**Comment by phr00t** [comment]
i'll try building on my end now with the changes, just to confirm everything is kosher

**Comment by phr00t** [comment]
Seems to build fine! Thank you for the help :)

**Pull request merged**
